name: .NET Core Deploy to IIS

on: 
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    # dotnet build and publish
    - name: Build with dotnet
      run: dotnet build --configuration Release .

    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o GeronimoUpdaterAPI .

    - name: Deploy to IIS
      run: |        
        if ( (Get-WebAppPoolState -Name geronimoupdaterAPI).value -contains "Started" ) {Stop-WebAppPool -Name geronimoupdaterAPI}
        Start-Sleep -s 3
        Copy-Item ./GeronimoUpdaterAPI/* C:/api/GeronimoUpdaterAPI -Recurse -Force
        Start-WebAppPool -Name geronimoupdaterAPI
